packages:
  - 'dist'

allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  less: true
  protobufjs: true

overrides:
  '@babel/core': '7.24.4'
